namespace Icegate.Integration.Models.Common;

/// <summary>Base type for all ICEGATE integration failures raised by our services.</summary>
public abstract class IcegateIntegrationException : Exception
{
    public string ErrorCode { get; }

    protected IcegateIntegrationException(string errorCode, string message, Exception? inner = null)
        : base(message, inner)
    {
        ErrorCode = errorCode;
    }
}

/// <summary>
/// A business/validation rejection from ICEGATE (e.g. invalid sender, invalid custodian code,
/// malformed JSON). Must NEVER be automatically retried.
/// </summary>
public class IcegateBusinessValidationException : IcegateIntegrationException
{
    public int HttpStatusCode { get; }

    public IcegateBusinessValidationException(string errorCode, string icegateMessage, int httpStatusCode = 422)
        : base(errorCode, icegateMessage)
    {
        HttpStatusCode = httpStatusCode;
    }
}

/// <summary>
/// Token missing / invalid / expired. Callers should clear the cached token, obtain a new one,
/// and retry the original request exactly once.
/// </summary>
public class IcegateTokenException : IcegateIntegrationException
{
    public IcegateTokenException(string errorCode, string message) : base(errorCode, message)
    {
    }
}

/// <summary>Transient network/timeout/5xx failure. Safe to retry with a controlled policy.</summary>
public class IcegateTransientException : IcegateIntegrationException
{
    public int? HttpStatusCode { get; }

    public IcegateTransientException(string errorCode, string message, int? httpStatusCode = null, Exception? inner = null)
        : base(errorCode, message, inner)
    {
        HttpStatusCode = httpStatusCode;
    }
}

/// <summary>The multipart response from ICEGATE could not be parsed as expected.</summary>
public class IcegateMultipartParseException : IcegateIntegrationException
{
    public IcegateMultipartParseException(string message, Exception? inner = null)
        : base(IcegateErrorCode.MalformedMultipart, message, inner)
    {
    }
}

/// <summary>The acknowledgement has not yet been generated by ICEGATE - caller should retry later.</summary>
public class IcegateAckNotYetAvailableException : IcegateIntegrationException
{
    public IcegateAckNotYetAvailableException(string message)
        : base(IcegateErrorCode.AckNotYetAvailable, message)
    {
    }
}

/// <summary>Raised when an endpoint required for the requested operation is still CONFIRM_WITH_ICEGATE.</summary>
public class IcegateEndpointNotConfirmedException : IcegateIntegrationException
{
    public IcegateEndpointNotConfirmedException(string settingName)
        : base(IcegateErrorCode.EndpointNotConfirmed,
            $"The ICEGATE endpoint for '{settingName}' has not been confirmed yet. " +
            "Update configuration once ICEGATE confirms the URL (see API Contract Document v1.6).")
    {
    }
}

/// <summary>Caller-side input validation failure on our own API (not an ICEGATE response).</summary>
public class IcegateRequestValidationException : IcegateIntegrationException
{
    public IcegateRequestValidationException(string errorCode, string message) : base(errorCode, message)
    {
    }
}
